[webapp_dist]
git-tree-sha1 = "054d1a31e8c96d059cee3b7b0c18e3909d30df06"
lazy = true

    [[webapp_dist.download]]
    sha256 = "6c03eb77f4e88d98be3f69d383dcc6a64598b9aee864b4da69b02023b2f7f426"
    url = "https://github.com/EnergyIntegration/EnergyIntegrationWebApp/releases/download/v0.1.2/EnergyIntegrationWebApp-0.1.2-dist.tar.gz"
